name: kunitz
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core Python and scientific computing
  - python=3.13.5
  - numpy=2.3.1
  - pandas=2.3.1
  - scipy=1.16.0
  - matplotlib=3.10.3
  - seaborn=0.13.2
  
  # Bioinformatics tools
  - biopython=1.85
  - blast=2.16.0
  - hmmer=3.4
  - mmseqs2=16.747c6
  - muscle=5.3
  - tmalign=20220227
  - seqkit=2.10.0
  - pdb-tools=2.5.0
  
  # Data handling and file processing
  - requests=2.32.4
  - wget=1.21.4
  - gawk=5.3.1
  
  # Essential system libraries
  - pip=25.1.1
  
  # Pip packages for additional functionality
  - pip:
      - pyyaml==6.0.2
